SELECT * FROM tabla_de_clientes;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS Limite FROM tabla_de_clientes
GROUP BY ESTADO;

SELECT * FROM tabla_de_productos;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS Mayo_Precio FROM tabla_de_productos
GROUP BY ENVASE;

SELECT ENVASE, COUNT(*) AS Cantidad FROM tabla_de_productos
GROUP BY ENVASE;

SELECT BARRIO, SUM(LIMITE_DE_CREDITO) as Limite FROM tabla_de_clientes
GROUP BY BARRIO;

SELECT BARRIO, SUM(LIMITE_DE_CREDITO) as Limite FROM tabla_de_clientes
WHERE CIUDAD = "Ciudad de México"
GROUP BY BARRIO;

SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) as Limite FROM tabla_de_clientes
WHERE CIUDAD = "Ciudad de México"
GROUP BY BARRIO;

SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) as Limite FROM tabla_de_clientes
WHERE CIUDAD = "Guadalajara"
GROUP BY BARRIO;

SELECT ESTADO, BARRIO, SUM(LIMITE_DE_CREDITO) as Limite FROM tabla_de_clientes
GROUP BY ESTADO, BARRIO;

SELECT ESTADO, BARRIO, MAX(LIMITE_DE_CREDITO) AS LIMITE, EDAD FROM tabla_de_clientes 
WHERE EDAD >= 20
GROUP BY ESTADO, BARRIO, EDAD
ORDER BY EDAD;

SELECT CODIGO_DEL_PRODUCTO, MAX(CANTIDAD) AS CANTIDAD_VENDIDA FROM items_facturas
WHERE CODIGO_DEL_PRODUCTO = 1101035
GROUP BY CODIGO_DEL_PRODUCTO;

SELECT COUNT(*) FROM items_facturas WHERE CODIGO_DEL_PRODUCTO = "1101035" AND CANTIDAD = 99;