SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes
GROUP BY ESTADO
HAVING LIMITE_TOTAL > 300000;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAX, MIN(PRECIO_DE_LISTA)	AS PRECIO_MIN FROM tabla_de_productos
GROUP BY ENVASE;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAX, MIN(PRECIO_DE_LISTA)	AS PRECIO_MIN FROM tabla_de_productos
GROUP BY ENVASE
HAVING SUM(PRECIO_DE_LISTA) > 80;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAX, MIN(PRECIO_DE_LISTA)	AS PRECIO_MIN FROM tabla_de_productos
GROUP BY ENVASE
HAVING SUM(PRECIO_DE_LISTA) >= 80 AND MAX(PRECIO_DE_LISTA) >= 5;

SELECT * FROM facturas;

SELECT DNI, count(*) AS CONTEO FROM facturas
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY DNI
HAVING CONTEO > 2000;