SELECT * FROM tabla_de_productos;

SELECT NOMBRE_DEL_PRODUCTO, PRECIO_DE_LISTA, 
CASE
	WHEN PRECIO_DE_LISTA >=12 THEN 'Costoso'
	WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'Asequible'
	ELSE 'Barato'
END AS PRECIO
FROM tabla_de_productos;

SELECT ENVASE, SABOR, TAMANO,
CASE
	WHEN PRECIO_DE_LISTA >=12 THEN 'Costoso'
	WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'Asequible'
	ELSE 'Barato'
END AS PRECIO, MIN(PRECIO_DE_LISTA) AS Precio_Minimo
FROM tabla_de_productos
WHERE TAMANO = '700 ml'
GROUP BY PRECIO, ENVASE, SABOR
ORDER BY ENVASE;

SELECT * FROM tabla_de_clientes;

SELECT NOMBRE,
CASE
	WHEN YEAR(FECHA_DE_NACIMIENTO) <= 1990 THEN 'Viejos'
    WHEN YEAR(FECHA_DE_NACIMIENTO) <= 1995 AND YEAR(FECHA_DE_NACIMIENTO) > 1990 THEN 'Jovenes'
    ELSE 'Niños'
END CLASIFICACION_EDAD
FROM tabla_de_clientes;
